/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biz.juvitec.princpal;

import biz.juvitec.mt.ModeloTablaSuperPiola;
import biz.juvitec.pruebatabla.FichaSalud;
import biz.juvitec.pruebatabla.Persona;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author fesquivelc
 */
public class ModeloTabla extends javax.swing.JFrame {

    /**
     * Creates new form ModeloTabla
     */
    private List<FichaSalud> lista;

    public ModeloTabla() {
        initComponents();
        iniciarData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEjemplo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEjemplo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEjemplo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblEjemploKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblEjemplo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private static final Logger LOG = Logger.getLogger(ModeloTabla.class.getName());

    private void tblEjemploKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblEjemploKeyReleased
        // TODO add your handling code here:
        int fila = tblEjemplo.getSelectedRow();
        int columna = tblEjemplo.getSelectedColumn();
        if(fila != -1 && columna != -1){
            FichaSalud ficha = lista.get(fila);
            LOG.info(ficha.toString());
        }
    }//GEN-LAST:event_tblEjemploKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModeloTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModeloTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModeloTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModeloTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModeloTabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEjemplo;
    // End of variables declaration//GEN-END:variables

    
    ObservableList<FichaSalud> lista2;
    private void iniciarData() {
        FichaSalud ficha;
        lista = new ArrayList<>();
        for (int i = 1; i <= 9; i++) {
            Persona persona = new Persona();
            persona.setDni("12345678" + i);
            persona.setNombre("NOMBRE " + i);
            persona.setApellidos("APELLIDOS " + i);
            
            ficha = new FichaSalud();
            ficha.setPersona(persona);
            ficha.setTieneAlergias(true);
            lista.add(ficha);
        }
        
//        setearConBinding(lista);
        lista2 = ObservableCollections.observableList(lista);
        
        
        ModeloTablaSuperPiola mt = new ModeloTablaSuperPiola(lista2);
        lista2.addObservableListListener(mt);
        this.tblEjemplo.setModel(mt);
    }

    private void setearConBinding(List<FichaSalud> lista) {
        lista = ObservableCollections.observableList(lista);
        
        BeanProperty pAlergia = BeanProperty.create("tieneAlergias");
        BeanProperty pTalla = BeanProperty.create("talla");
        BeanProperty pPeso = BeanProperty.create("peso");
        BeanProperty pEdad = BeanProperty.create("edad");
        
        JTableBinding binding = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ_ONCE, lista, tblEjemplo);
        
        binding.addColumnBinding(pAlergia).setColumnName("TieneAlergias").setEditable(true).setColumnClass(Boolean.class);
        binding.addColumnBinding(pTalla).setColumnName("Talla").setEditable(true).setColumnClass(Double.class);
        binding.addColumnBinding(pPeso).setColumnName("Peso").setEditable(true).setColumnClass(Double.class);
        binding.addColumnBinding(pEdad).setColumnName("Edad").setEditable(true).setColumnClass(Integer.class);
        
        
        binding.bind();
    }
}
